# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5806d58aa47058c823c21d0ca93e2814"
name = "abcd"
application_url = "https://hollywood-managers-set-trio.trycloudflare.com/admin.html"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_app_proxy,write_app_proxy,read_validations,write_validations,read_files,write_files,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_online_store_navigation,write_online_store_navigation,read_online_store_pages,write_online_store_pages,read_products,write_products,read_publications,write_publications,read_content,write_content,write_theme_code,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "https://hollywood-managers-set-trio.trycloudflare.com/api/shopify/proxy"
subpath = "amazon-customizer"
prefix = "apps"
