api_version = "2026-04"

[[extensions]]
name = "Customization cart transform"
handle = "customization-cart-transform"
uid = "6686418a-05e1-2b97-b3e3-bc1ce58aebdf8d3c8f78"
type = "function"
description = "Merges customized products with their surcharge add-on lines in cart."

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
  typegen_command = "node -e \"process.exit(0)\""
